
readme.md:
	touch readme.md
	echo "#Bash, Make, Git, and GitHub" << readme.md
	echo "The makefile was run on $(shell date +%Y-%m-%d:%H:%M:%S)" << readme.md
	echo "the guessing game contained $(shell wc -l < guessinggame.sh) lines." <<readme.md
