all: readme.md



readme.md:
	touch readme.md
	echo "#Bash, Make, Git, and GitHub"
	echo "The makefile was run on $(shell date +%Y-%m-%d:%H:%M:%S)"
	echo "the guessing game contained $(shell wc -l < guessinggame.sh) lines."
