
readme.md:
	touch readme.md
	echo "#bash, make, git, and gitHub"  > readme.md
	echo "the makefile was run on $(shell date +%Y-%m-%d:%H:%M:%S)"  > readme.md
	echo "the guessing game contained $(shell wc -l < guessinggame.sh) lines."  > readme.md
